import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SushiCartProvider } from "@context/SushiCartContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <SushiCartProvider>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </SushiCartProvider>
  );
}
