export const sushiPlates = [
  {
    name: "California Roll",
    price: 12.99,
    color: "bg-red-500",
    description: "Roll with cucumber, avocado, crab, and Japanese mayo.",
    img: "/assets/california-roll.jpg",
  },
  {
    name: "Salmon Nigiri",
    price: 8.99,
    color: "bg-blue-500",
    description: "Fresh salmon on a bed of sushi rice.",
    img: "/assets/salmon-nigiri.jpg",
  },
  {
    name: "Spicy Tuna Maki",
    price: 10.99,
    color: "bg-green-500",
    description: "Spicy fresh tuna wrapped in nori and sushi rice.",
    img: "/assets/spicy-tuna-maki.jpg",
  },
  {
    name: "Tempura Uramaki",
    price: 14.99,
    color: "bg-purple-500",
    description: "Inside-out roll with tempura shrimp, avocado, and spicy mayo.",
    img: "/assets/tempura-uramaki.jpg",
  },
  {
    name: "Octopus Sashimi",
    price: 9.99,
    color: "bg-yellow-500",
    description: "Thin slices of fresh octopus served with ponzu sauce.",
    img: "/assets/octopus-sashimi.jpg",
  },
  {
    name: "Ikura Gunkan",
    price: 11.99,
    color: "bg-pink-500",
    description: "Nori rolled into a ship shape with salmon roe.",
    img: "/assets/ikura-gunkan.jpg",
  },
  {
    name: "Salmon Tartare",
    price: 13.99,
    color: "bg-orange-500",
    description: "Chopped raw salmon with avocado, red onion, and soy sauce.",
    img: "/assets/salmon-tartare.jpg",
  },
  {
    name: "Dragon Roll",
    price: 16.99,
    color: "bg-teal-500",
    description: "Roll with tempura prawn, avocado, cucumber, and eel sauce.",
    img: "/assets/dragon-roll.jpg",
  },
  {
    name: "Vegetable Futomaki",
    price: 10.99,
    color: "bg-indigo-500",
    description: "Roll filled with carrot, cucumber, avocado, mango, and teriyaki sauce.",
    img: "/assets/vegetable-futomaki.jpg",
  },
  {
    name: "Yellowtail Nigiri",
    price: 11.99,
    color: "bg-red-500",
    description: "Fresh yellowtail on lightly seasoned sushi rice.",
    img: "/assets/yellowtail-nigiri.jpg",
  },
  {
    name: "Philadelphia Roll",
    price: 9.99,
    color: "bg-blue-500",
    description: "Roll with salmon, cream cheese, and scallions.",
    img: "/assets/philadelphia-roll.jpg",
  },
  {
    name: "Mango Tempura Maki",
    price: 12.99,
    color: "bg-green-500",
    description: "Fresh mango tempura wrapped in nori and sushi rice.",
    img: "/assets/mango-tempura-maki.jpg",
  }
];